sudo: required
services:
    - docker

script:
    - docker build -t hgeissler/ci_node .
    - docker images hgeissler/ci_node

before_deploy:
    - docker login -u hgeissler -password-stdin
    
deploy:
    provider: script
    script: docker push hgeissler/ci_node
    on:
        branch: master
